apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tachyon.fullname" . }}-keys
  labels:
    {{- include "tachyon.labels" . | nindent 4 }}
type: Opaque
data:
  private-key: {{ .Values.secrets.privateKey | b64enc | quote }}
  peer-public-key: {{ .Values.secrets.peerPublicKey | b64enc | quote }}
  psk: {{ .Values.secrets.psk | b64enc | quote }}
