{{- if and .Values.metrics.enabled .Values.metrics.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "tachyon.fullname" . }}
  labels:
    {{- include "tachyon.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "tachyon.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
{{- end }}
